language: go

sudo: false

go:
  - 1.8

install:
  - go get github.com/golang/dep/...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - cd .. && mkdir src && mv avatar src/avatar && cd src/avatar
  - $HOME/gopath/bin/dep ensure

script:
  - go test . -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN


