[[dependencies]]
  branch = "master"
  name = "github.com/golang/freetype"

[[dependencies]]
  branch = "master"
  name = "github.com/nfnt/resize"

[[dependencies]]
  name = "github.com/stretchr/testify"
  version = "v1.1.4"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/image"
